import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requireAdmin } from '@/lib/admin-auth';
import { createSupabaseAdminClient } from '@/lib/supabase/admin-client';

const actionSchema = z.object({ id: z.string().uuid(), action: z.enum(['approve','reject']) });
export async function GET() { const admin = await requireAdmin(); if (!admin) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); const supabase = createSupabaseAdminClient(); const { data, error } = await supabase.from('affiliate_product_candidates').select('*').in('status',['pending','approved']).order('score',{ ascending:false }).limit(250); return error ? NextResponse.json({ error: 'Could not load candidates.' }, { status:500 }) : NextResponse.json(data,{ headers:{'Cache-Control':'no-store'} }); }
export async function POST(request: Request) {
  const admin = await requireAdmin(); if (!admin) return NextResponse.json({ error:'Unauthorized.' },{status:401}); const parsed=actionSchema.safeParse(await request.json().catch(()=>null)); if(!parsed.success) return NextResponse.json({error:'Invalid review action.'},{status:400});
  const supabase=createSupabaseAdminClient(); const {data:candidate,error}=await supabase.from('affiliate_product_candidates').select('*').eq('id',parsed.data.id).single(); if(error||!candidate) return NextResponse.json({error:'Candidate not found.'},{status:404});
  if(parsed.data.action==='reject'){ await supabase.from('affiliate_product_candidates').update({status:'rejected',reviewed_at:new Date().toISOString()}).eq('id',candidate.id); await supabase.from('admin_audit_log').insert({actor_email:admin.email,action:'scout_reject',entity_type:'affiliate_candidate',entity_id:candidate.id}); return NextResponse.json({ok:true}); }
  const suffix=String(candidate.id).slice(0,8); const slug=`${String(candidate.name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,68)}-${suffix}`; const id=`kn-aff-${candidate.id}`;
  const {error:productError}=await supabase.from('catalog_products').upsert({id,name:candidate.name,slug,category:candidate.category||'Approved Partner Pick',ritual_type:'Kunta Naturals Pick',audience:'Adults',product_type:'affiliate',short_description:candidate.description.slice(0,260)||`An approved ${candidate.merchant_name} partner product.`,description:candidate.description,price:candidate.price,currency:candidate.currency,image_url:candidate.image_url,detail_url:'',affiliate_url:candidate.affiliate_url,vendor_name:candidate.merchant_name,affiliate_disclosure:'Kunta Naturals may earn a commission at no extra cost to you.',checkout_status:'live',fulfillment_model:'partner_affiliate',tags:['affiliate','scout-approved'],status:'review',sort_order:500,updated_at:new Date().toISOString()},{onConflict:'id'}); if(productError)return NextResponse.json({error:'Could not prepare the catalog draft.'},{status:500});
  await supabase.from('affiliate_product_candidates').update({status:'imported',reviewed_at:new Date().toISOString()}).eq('id',candidate.id); await supabase.from('admin_audit_log').insert({actor_email:admin.email,action:'scout_import',entity_type:'catalog_product',entity_id:id,metadata:{candidate_id:candidate.id,score:candidate.score}}); return NextResponse.json({ok:true,productId:id});
}
