'use client';
import { FormEvent, useEffect, useState } from 'react';
type Media = { name: string; url: string };
export function MediaManager() {
  const [items, setItems] = useState<Media[]>([]); const [message, setMessage] = useState('Loading media…'); const [busy, setBusy] = useState(false);
  async function load() { try { const r = await fetch('/api/admin/media', { cache: 'no-store' }); if (r.status === 401 || r.status === 403) { location.href = '/login?next=%2Fmedia'; return; } const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Could not load media.'); setItems(d); setMessage(`${d.length} media files loaded.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not load media. Check your connection and try again.'); } }
  useEffect(() => { void load(); }, []);
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage('Uploading…'); const form = event.currentTarget; try { const r = await fetch('/api/admin/media', { method: 'POST', body: new FormData(form) }); if (r.status === 401 || r.status === 403) { location.href = '/login?next=%2Fmedia'; return; } const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Upload failed.'); form.reset(); await load(); setMessage('Uploaded. Copy its URL into a product image field.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Upload failed. The selected file is unchanged; try again.'); } finally { setBusy(false); } }
  async function copyUrl(url: string) { try { await navigator.clipboard.writeText(url); setMessage('Media URL copied.'); } catch { setMessage('Copy was blocked by the browser. Open the image and copy its address instead.'); } }
  return <><form className="card form-grid" onSubmit={upload}><label>Brand image<input className="input" name="file" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" required /></label><p>PNG, JPEG, WebP, or SVG · 10 MB maximum. Upload only media you own or are licensed to use.</p><button disabled={busy}>{busy ? 'Uploading…' : 'Upload image'}</button><p className="notice" role="status">{message}</p></form><section className="media-grid">{items.length === 0 && <div className="card empty-state"><h2>No media uploaded</h2><p>Upload a licensed brand image to make it available to product editors.</p></div>}{items.map((item) => <article className="card" key={item.name}><img src={item.url} alt={item.name} /><strong>{item.name}</strong><button className="button-secondary" type="button" onClick={() => void copyUrl(item.url)}>Copy URL</button></article>)}</section></>;
}
